

x-global-env: &global-env
  PG_USER: app_user
  PG_PASSWORD: app_password
  PG_HOST: postgres_db
  PG_PORT: 5432
  PG_DATABASE: almuerzos_db
  RABBITMQ_URL: amqp://rabbitmq:5672
  
  EXCHANGE_NUEVA_ORDEN: nueva.orden.ex
  ROUTING_KEY_NUEVA_ORDEN: nueva_orden
  QUEUE_NUEVA_ORDEN: nueva.orden.qu

  EXCHANGE_ESTADO_ORDEN: estado.orden.ex
  ROUTING_KEY_ESTADO_ORDEN: estado
  QUEUE_ESTADO_ORDEN: estado.orden.qu

  EXCHANGE_SOLICITUD_COMPRA: solicitud.compra.ex
  ROUTING_KEY_SOLICITUD_COMPRA: solicitud_compra
  QUEUE_SOLICITUD_COMPRA: solicitud.compra.qu

  EXCHANGE_RESPUESTA_COMPRA: respuesta.compra.ex
  ROUTING_KEY_RESPUESTA_COMPRA: respuesta_compra
  QUEUE_RESPUESTA_COMPRA: respuesta.compra.qu
services:
  nginx:
    image: nginx:latest
    container_name: nginx_frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - orchestator
    networks:
      - app_network

  orchestator:
    build: ./orchestator_ms
    ports:
      - "8080:8080"
    container_name: orchestator_ms
    environment:
      <<: *global-env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app_network

  kitchen-manage:
    build: ./kitchen_manage_ms
    container_name: kitchen_manage_ms
    environment:
      <<: *global-env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app_network

  logistic-inventory:
    build: ./logistic_inventory_ms
    container_name: logistic_inventory_ms
    environment:
      <<: *global-env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: almuerzos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      #- ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro 
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro  
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_LOAD_DEFINITIONS=true
      - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/definitions.json  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
